apiVersion: v1
kind: Pod
metadata:
  name: gameoflife
  labels:
    env: dev
    app: gol
spec:
  containers:
  - name: gameoflife
    image: veerendradevops/gol_tomcat
    ports:
    - containerPort: 8080
