apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    tier: frontend 
spec:  
  containers:
    - name: nginx       
      image: nginx:latest   	# Update the nginx container from Ver. 1.7.9 to the latest
      ports:
        - containerPort: 80
